#!/bin/bash

echo '---------------------------'
echo 'Killing previous executions'
echo '---------------------------'


rm $HOME/simulation/results/*.m
rm $HOME/simulation/results/*.txt

killmymodules
killmymodules

pkill tclserv
pkill eltclsh
pkill tclserv
pkill eltclsh

h2 end
h2 end

echo '--------------------'
echo 'Initilizing pocolibs'
echo '--------------------'

h2 init

echo '-----------------------'
echo 'Initilizing rfid module'
echo '-----------------------'
sleep 1
$HOME/workspace/rfidLocMapBin/Linux/bin/rfidLocMap -b
sleep 1


echo '----------------------'
echo 'Initilizing TCL server'
echo '----------------------'


tclserv
sleep 1

eltclsh testLocMapFile.tcl -package genom 

echo '-----------------------'
echo 'End'
echo '-----------------------'
